---
# === 1. Désactiver le pare-feu firewalld ===
- name: Désactiver firewalld (pare-feu par défaut sur Red Hat)
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true

# === 2. Mise à jour du système ===
- name: Mettre à jour tous les paquets
  yum:
    name: "*"
    state: latest

# Installer EPEL pour RHEL/CentOS 9
#- name: Installer epel-release via URL pour RHEL/CentOS 9
#  command: dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

- name: Installer les dépendances nécessaires
  yum:
    name:
      - curl
      - tar
      - socat
      - conntrack-tools
      - iptables
      - ca-certificates
      - nfs-utils
    state: present

# === 3. Désactiver le swap (nécessaire pour Kubernetes) ===
- name: Désactiver le swap immédiatement
  command: swapoff -a
  ignore_errors: true

- name: Désactiver le swap au redémarrage
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '# \1'
  ignore_errors: true

# === 4. Désactiver SELinux définitivement ===
- name: Désactiver SELinux dans /etc/selinux/config
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: 'SELINUX=disabled'

# === 5. Vérifier SElinux est désactivé
- name: Vérifier l'état de SELinux
  command: getenforce
  register: selinux_status
  ignore_errors: true

- debug:
    msg: "État SELinux actuel: {{ selinux_status.stdout }}"

# === 6. Nettoyage ===
- name: Nettoyer les paquets inutiles
  yum:
    autoremove: yes
