$ANSIBLE_VAULT;1.1;AES256
39663138616533353035343934643161303966626138643639646662323864343037383063313165
3131383434663664366232346334346434373261393333390a306466333862373835373036333165
64663462313435336136353533346564373030613963656561306631383433353134613765336363
3661366165613631610a643864316235613239343264303163313831666239616638393032633462
66373837646137376633376134613363313833663361623061333334343837626637323466366538
62343534646463623665626536336630663337326131666132313037353239336332633338333538
65663832653761643436373234613961373362636434306337373537323864363462303733386333
33386539366239353366
